## Path to sample sheet
samplesheet: 'samplesheet.txt'

## List columns to group (i.e. any columns left out will become part of the same group)
mergeBy: ['Project', 'Cell_Type']

## Genome-specific reference parameters
fasta: '/fdb/igenomes/Homo_sapiens/NCBI/GRCh38/Sequence/BWAIndex/genome.fa' 
chromSizes: '/data/genome/fasta/hg38.chrom.sizes'
