## Path to sample sheet
samplesheet: 'samplesheet.txt'

## List columns to group (i.e. any columns left out will become part of the same group)
mergeBy: ['Project', 'Cell_Type', 'Bio_Rep', 'Tech_Rep']

## Genome-specific reference parameters
fasta: '/fdb/bwa/indexes/hg38.fa' 
chromSizes: '/data/genome/fasta/hg38.chrom.sizes'
